name: OIDC test with kind
on: workflow_dispatch
jobs:
  kind:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Create k8s cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: config.yaml
      - name: Add oidc user
        run: |
          kubectl config set-credentials oidc \
          --token=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL | jq -r .value)
      - name: Forbidden
        run: "! kubectl --user=oidc get pod"
      - name: Create role/rolebinding for oidc user
        run: |
          kubectl create -n kube-system role oidc --verb=list --resource=pods
          kubectl create -n kube-system rolebinding oidc --role=oidc --user=github-actions:bgpat/gha-oidc-k8s-example
      - name: Success
        run: kubectl --user=oidc -n kube-system get pod
